/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Home',
    },
    {
      type: 'doc',
      id: 'quickstart',
      label: 'Get Started',
    },
    {
      type: 'doc',
      id: 'why-dbos',
      label: 'Why DBOS?',
    },
    {
      type: 'doc',
      id: 'architecture',
      label: 'DBOS Architecture',
    },
    {
      type: 'category',
      label: 'Develop with Python',
      items: [
        {
          type: 'autogenerated',
          dirName: 'python',
        }
      ],
    },
    {
      type: 'category',
      label: 'Develop with TypeScript',
      items: [
        {
          type: 'autogenerated',
          dirName: 'typescript',
        }
      ],
    },
    {
      type: 'category',
      label: 'Develop with Go',
      items: [
        'golang/integrating-dbos',
        'golang/programming-guide',
        {
          type: 'category',
          label: 'Tutorials',
          items: [
            {
              type: 'autogenerated',
              dirName: 'golang/tutorials',
            }
          ],
        },
        {
          type: 'category',
          label: 'Reference',
          items: [
            'golang/reference/dbos-context',
            'golang/reference/workflows-steps',
            'golang/reference/methods',
            'golang/reference/queues',
            'golang/reference/client',
            {
              type: 'link',
              label: 'DBOS CLI',
              href: 'https://pkg.go.dev/github.com/dbos-inc/dbos-transact-golang/cmd/dbos#section-readme',
            },
          ],
        },
        {
          type: 'category',
          label: 'Examples',
          items: [
            {
              type: 'autogenerated',
              dirName: 'golang/examples',
            }
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Deploy To Production',
      items: [
        {
          type: 'autogenerated',
          dirName: 'production',
        }
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [
        {
          type: 'autogenerated',
          dirName: 'integrations',
        }
      ],
    },
    {
      type: 'category',
      label: 'Concepts and Explanations',
      items: [
        {
          type: 'autogenerated',
          dirName: 'explanations',
        }
      ],
    },
    {
      type: 'doc',
      id: 'faq',
      label: 'Troubleshooting & FAQ',
    },
  ],

  examplesSidebar: [
    {
      type: 'doc',
      id: 'examples/index',
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Python Examples',
      items: [
        {
          type: 'autogenerated',
          dirName: 'python/examples',
        }
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'TypeScript Examples',
      items: [
        {
          type: 'autogenerated',
          dirName: 'typescript/examples',
        }
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Go Examples',
      items: [
        {
          type: 'autogenerated',
          dirName: 'golang/examples',
        }
      ],
      collapsed: false,
    }
  ],
};

module.exports = sidebars;
